# Generated by Django 4.1.7 on 2024-03-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_about_me_alter_profile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="London", max_length=180, verbose_name="city"
            ),
        ),
    ]
